# Generated by Django 4.1.2 on 2022-10-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CDescription',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='CObjectives',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='COutcomes',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Cost',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
