# Generated by Django 4.1.2 on 2022-10-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=150)),
                ('ConfirmPassword', models.CharField(max_length=150)),
            ],
        ),
    ]
